# Generated by scripts/generate_test_dockerfile.py — do not edit manually.
# Re-run the script after adding or modifying a connector's Dockerfile.extra.
FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN find connectors -name requirements.txt -exec pip install --no-cache-dir -r {} \;

ENTRYPOINT ["pytest"]
