#!/usr/bin/env python3
"""Generate the test Dockerfile from connector Dockerfile.extra files.

Run this after adding or changing a connector's Dockerfile.extra:

    python scripts/generate_test_dockerfile.py

The generated Dockerfile is checked in so that ``docker compose build``
works without an extra step for people who haven't changed connectors.
"""
import glob
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCKERFILE_PATH = os.path.join(REPO_ROOT, "Dockerfile")

AGENT_TYPE = "generic"

HEADER = """\
# Generated by scripts/generate_test_dockerfile.py — do not edit manually.
# Re-run the script after adding or modifying a connector's Dockerfile.extra.
ARG BASE_IMAGE=montecarlodata/agent:latest-{agent_type}
FROM $BASE_IMAGE

USER root
"""

FOOTER = """\
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN find connectors -name requirements.txt -exec pip install --no-cache-dir -r {} \\;

ENTRYPOINT ["pytest"]
"""


def main():
    extras = sorted(glob.glob(os.path.join(REPO_ROOT, "connectors", "*", "Dockerfile.extra")))

    lines = [HEADER.format(agent_type=AGENT_TYPE)]
    included = []
    for path in extras:
        name = os.path.basename(os.path.dirname(path))
        with open(path) as f:
            content = f.read().strip()
        # Skip files that contain only comments and whitespace
        has_instructions = any(
            line.strip() and not line.strip().startswith("#")
            for line in content.splitlines()
        )
        if content and has_instructions:
            lines.append(f"# From connectors/{name}/Dockerfile.extra")
            lines.append(content)
            lines.append("")
            included.append(name)

    lines.append(FOOTER)

    dockerfile = "\n".join(lines)

    with open(DOCKERFILE_PATH, "w") as f:
        f.write(dockerfile)

    if included:
        print(f"Dockerfile generated with extras from: {', '.join(included)}")
    else:
        print("Dockerfile generated (no Dockerfile.extra instructions found)")


if __name__ == "__main__":
    main()
