#!/usr/bin/env python3
"""Generate the test Dockerfile from connector Dockerfile.extra files.

Run this after adding or changing a connector's Dockerfile.extra:

    python scripts/generate_test_dockerfile.py

The generated Dockerfile is checked in so that ``docker compose build``
works without an extra step for people who haven't changed connectors.
"""
import glob
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCKERFILE_PATH = os.path.join(REPO_ROOT, "Dockerfile")

AGENT_TYPE = "generic"

HEADER = """\
# Generated by scripts/generate_test_dockerfile.py — do not edit manually.
# Re-run the script after adding or modifying a connector's Dockerfile.extra.
ARG BASE_IMAGE=montecarlodata/agent:latest-{agent_type}
FROM $BASE_IMAGE

USER root
"""


def _build_footer():
    """Build the FOOTER dynamically, conditionally including ETL requirements installation."""
    footer_lines = [
        "WORKDIR /app",
        "",
        "COPY requirements.txt .",
        "RUN pip install --no-cache-dir -r requirements.txt",
        "",
        "COPY . .",
        "",
        "RUN find connectors -name requirements.txt -exec pip install --no-cache-dir -r {} \\;",
    ]

    has_etl_requirements = bool(
        glob.glob(os.path.join(REPO_ROOT, "etl_connectors", "*", "requirements.txt"))
    )
    if has_etl_requirements:
        footer_lines.append(
            "RUN find etl_connectors -name requirements.txt -exec pip install --no-cache-dir -r {} \\;"
        )

    footer_lines.append("")
    footer_lines.append('ENTRYPOINT ["pytest"]')
    footer_lines.append("")

    return "\n".join(footer_lines)


def main():
    connector_extras = sorted(
        glob.glob(os.path.join(REPO_ROOT, "connectors", "*", "Dockerfile.extra"))
    )
    etl_extras = sorted(
        glob.glob(os.path.join(REPO_ROOT, "etl_connectors", "*", "Dockerfile.extra"))
    )

    lines = [HEADER.format(agent_type=AGENT_TYPE)]
    included = []
    etl_included = []

    for path in connector_extras:
        name = os.path.basename(os.path.dirname(path))
        with open(path) as f:
            content = f.read().strip()
        # Skip files that contain only comments and whitespace
        has_instructions = any(
            line.strip() and not line.strip().startswith("#")
            for line in content.splitlines()
        )
        if content and has_instructions:
            lines.append(f"# From connectors/{name}/Dockerfile.extra")
            lines.append(content)
            lines.append("")
            included.append(name)

    for path in etl_extras:
        name = os.path.basename(os.path.dirname(path))
        with open(path) as f:
            content = f.read().strip()
        # Skip files that contain only comments and whitespace
        has_instructions = any(
            line.strip() and not line.strip().startswith("#")
            for line in content.splitlines()
        )
        if content and has_instructions:
            lines.append(f"# From etl_connectors/{name}/Dockerfile.extra")
            lines.append(content)
            lines.append("")
            etl_included.append(name)

    lines.append(_build_footer())

    dockerfile = "\n".join(lines)

    with open(DOCKERFILE_PATH, "w") as f:
        f.write(dockerfile)

    all_included = included + etl_included
    if all_included:
        print(f"Dockerfile generated with extras from: {', '.join(all_included)}")
    else:
        print("Dockerfile generated (no Dockerfile.extra instructions found)")


if __name__ == "__main__":
    main()
