#!/usr/bin/env python3
"""Generate the test Dockerfile from connector Dockerfile.extra files.

Run this after adding or changing a connector's Dockerfile.extra:

    python scripts/generate_test_dockerfile.py

The generated Dockerfile is checked in so that ``docker compose build``
works without an extra step for people who haven't changed connectors.
"""
import glob
import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCKERFILE_PATH = os.path.join(REPO_ROOT, "Dockerfile")

AGENT_TYPE = "generic"

HEADER = """\
# Generated by scripts/generate_test_dockerfile.py — do not edit manually.
# Re-run the script after adding or modifying a connector's Dockerfile.extra.
ARG BASE_IMAGE=montecarlodata/agent:latest-{agent_type}
FROM $BASE_IMAGE

USER root
"""


def _build_footer():
    """Build the FOOTER dynamically, conditionally including ETL requirements installation."""
    footer_lines = [
        "WORKDIR /app",
        "",
        "COPY requirements.txt .",
        "RUN pip install --no-cache-dir -r requirements.txt",
        "",
        "COPY . .",
        "",
        "RUN find connectors -name requirements.txt -exec pip install --no-cache-dir -r {} \\;",
        # The family dirs are git-tracked, so these lines are emitted
        # unconditionally: gating them on a */requirements.txt existing at
        # generation time makes the output machine-dependent (a fresh
        # checkout would delete them from the committed Dockerfile).
        "RUN find etl_connectors -name requirements.txt -exec pip install --no-cache-dir -r {} \\;",
        "RUN find bi_connectors -name requirements.txt -exec pip install --no-cache-dir -r {} \\;",
    ]

    footer_lines.append("")
    footer_lines.append('ENTRYPOINT ["pytest"]')
    footer_lines.append("")

    return "\n".join(footer_lines)


def main():
    lines = [HEADER.format(agent_type=AGENT_TYPE)]
    included = []

    # Collect Dockerfile.extra system-dependency instructions across all three
    # connector families, in a stable family order.
    for family in ("connectors", "etl_connectors", "bi_connectors"):
        for path in sorted(
            glob.glob(os.path.join(REPO_ROOT, family, "*", "Dockerfile.extra"))
        ):
            name = os.path.basename(os.path.dirname(path))
            with open(path) as f:
                content = f.read().strip()
            # Skip files that contain only comments and whitespace
            has_instructions = any(
                line.strip() and not line.strip().startswith("#")
                for line in content.splitlines()
            )
            if content and has_instructions:
                lines.append(f"# From {family}/{name}/Dockerfile.extra")
                lines.append(content)
                lines.append("")
                included.append(f"{family}/{name}")

    lines.append(_build_footer())

    dockerfile = "\n".join(lines)

    with open(DOCKERFILE_PATH, "w") as f:
        f.write(dockerfile)

    if included:
        print(f"Dockerfile generated with extras from: {', '.join(included)}")
    else:
        print("Dockerfile generated (no Dockerfile.extra instructions found)")


if __name__ == "__main__":
    main()
